### ISSUE TITLE
Model Specifications

### ISSUE THREAD

**Issue by BorisAnc** [OlafenwaMoses/DeepStack_OpenLogo#1]
Hello,

Thanks for your great work.
I've seen that you're using a Yolov5x model.
For how many epochs was it trained ?
Did you change the default config files ?

Thanks in advance,

Best

**Comment by OlafenwaMoses** [comment]
The model was trained for 35 epochs with no changes to the config files. The notebook detailed in the link below as used as-is

https://docs.deepstack.cc/custom-models/training/index.html#option-1-training-on-google-colab-with-free-gpus

At 35 epochs, the model achieved 0.75 map@.5 and 0.53 map@.95

**Comment by BorisAnc** [comment]
Perfect. Thanks for your quick answer !
Good model performance :)

**Comment by OlafenwaMoses** [comment]
You are welcome @BorisAnc .
