### ISSUE TITLE
USPS

### ISSUE THREAD

**Issue by iankaufmann** [OlafenwaMoses/DeepStack_OpenLogo#2]
Hello!  This is a great piece of work!  

I'm surprised that USPS is not on the list.  I have been trying to research what I would need to do to accomplish complete package/mail delivery detection via Blue Iris and Deepstack and am inspired by your work.  This works perfectly for FedEx and UPS trucks.

It would be so awesome if it included USPS.  Also, the Amazon Prime trucks at least in my area don't actually have the traditional Amazon logo on them, just the "Prime" logo.

I don't know if there is any way to enhance this with USPS and Prime logos, or if you can release the data that you trained this with so that I can add to it and run the training myself.

I'm not really asking, just throwing it out there.  I have tried my hand at it and it hasn't worked as well as what you've come up with here.

My end goal is to combine my driveway camera with deepstack and home assistant mail-and-packages custom integration to get notifications when a delivery truck is present AND home assistant knows when a package is scheduled for delivery (and not just driving by).

**Comment by OlafenwaMoses** [comment]
@iankaufmann Thanks for the compliment. **USPS** is not on the list for this model because the dataset ( [OpenLogo](https://qmul-openlogo.github.io/) ) it was trained on doesn't contain the USPS logo.

However, you can create a new DeepStack custom model for detecting the USPS logo or any other object you want to detect by doing the following.

- get training images by scrapping the web for images of USPS vehicles (e.g images from [here](https://www.google.com/search?q=usps+vehicles&sxsrf=ALeKk02sBXIn8yhv2j6QwdNLR9oSPJ5fXg:1620085910927&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj2teep2q7wAhUK8BQKHX4DBEwQ_AUoAXoECAEQAw&biw=1504&bih=860))
- Follow the DeepStack custom model documentation to train and create the model using Google Colab's free GPU https://docs.deepstack.cc/custom-models/

**Comment by iankaufmann** [comment]
Interesting... I guess I didn't realize that it was a pre-existing dataset.  

I'm new to this and Deepstack has been the only thing I've worked with since it works well with Blue Iris and AI Tool.  I see now that this OpenLogo dataset exists outside of Deepstack and your repo was tying them together.

I was messing around with the stuff in the link you provided last night and running it on Google Colab.  It was mildly successful with regular photography but I couldn't get it to work with my driveway cam.  I know I just need to add more images and run the training more times.

I just thought that OpenLogo worked so well with my sample images of FedEx that I'd ask... but that makes perfect sense that it's not your dataset.  

Thanks for writing back so quickly!  I will just have to try again!

**Comment by OlafenwaMoses** [comment]
You are most welcome. With 200-400 images , you should be able to get a good custom model for detecting USPS logo.

**Comment by sstratoti** [comment]
@iankaufmann any luck with getting the USPS logo trained? I've got deepstack detection working with UPS, Fedex and almost amazon - USPS is the missing piece. :)

**Comment by iankaufmann** [comment]
@sstratoti, I was not able to get USPS trained reliably with my own datasets on Deepstack.  

I tried a couple of times a year ago and gave up.  What I ended up doing was running the [Sighthound ALPR docker](https://hub.docker.com/r/sighthound/alpr/tags) and that does a fantastic job at detecting the USPS truck.  The only issue is that it doesn't have a direct way to interact with the data, you just see it on a dashboard.

However, I stumbled upon a log file that the detections are written to, so I wrote a bash script that processes that file and exports the data over MQTT, which can trigger Blue Iris and be read by Home Assistant.

It's a pretty crazy setup but has been giving me reliable mail truck alerts for the past year without much fuss after the initial weeks of tuning and debugging.

It basically goes: Blue Iris motion detected near the mailbox -> JPEG that goes into AI Tool/Deepstack for the basic vehicle detection -> if it's a vehicle the JPEG is copied into the Sighthound watch directory -> bash daemon that is watching (`tail -f camo.log investigator.log`) the log file for references to the USPS truck -> MQTT trigger on the Blue Iris camera to provide the alert and snapshot -> Home Assistant binary sensor for "Mail Delivered Today" turns on.

I honestly can't believe it works, and is probably not what Sighthound intended, but that docker hasn't been updated in 2 years and I haven't touched the setup in almost a year.

**Comment by sstratoti** [comment]
@iankaufmann I'm actually creating the custom model right now using the steps above :) If it works, I'll throw it up in a github repo and will link it here.

**Comment by sstratoti** [comment]
@iankaufmann 
Here ya go! Seems to be working fine so far! HTH!
https://github.com/sstratoti/DeepStack_USPS

**Comment by iankaufmann** [comment]
> @iankaufmann Here ya go! Seems to be working fine so far! HTH! https://github.com/sstratoti/DeepStack_USPS

Nice!  I will definitely check it out.  I like my setup because it gives me a lot more detailed car info on all of the other cars that drive by (specific make, model, color), which wasn't what I was out for, but now I'm pretty used to having that running log and it's just cool.  However, it definitely wouldn't hurt to catch it at the AI Tool/Deepstack layer and could add some redundancy as well.

Thanks for making it available!

**Comment by OlafenwaMoses** [comment]
@sstratoti Awesome work you have done with **DeepStack_USPS**. We will add it to our documentation page here https://docs.deepstack.cc/custom-models-samples/

@iankaufmann If you will like to have a more detailed vehicle detection model that gives make, model and colour with the detection, we will gladly work on adding this to DeepStack as soon as we can.

You can create an issue for this on the DeepStack repository
https://github.com/johnolafenwa/DeepStack
